### ISSUE TITLE
Hypothesis 

### ISSUE THREAD

**Issue by Gahamelas** [novoid/Memacs#102]
Hi, I checked that Orger has a module for hypothesis. Do you think you will be adding one?
And another question is how is Orger different in goal than memacs?
Both convert to ORG different types of data. So what is the core difference?
Thanks!

**Comment by novoid** [comment]
Hi,
Please do read [the README of Orger](https://github.com/karlicoss/orger) to learn about differences between Memacs and Orger.
We both developed the projects to solve personal requirements by including non-Org data into Org mode somehow. Memacs is much older and Orger follows a different perspective. Orger was developed without being aware of the existance of Memacs.
I don't know what hypothesis is and I'm currently not planning on adding additional Memacs modules. However, I'm happy to accept pull-requests for additional modules. All recent modules were implemented by others, re-using the Memacs framework that is optimized for providing a concept to implement a Memacs module with minimal effort.
