### ISSUE TITLE
Can't parse timestamp

### ISSUE THREAD

**Issue by ArchGalileu** [novoid/Memacs#111]
I'm very amazed with your website... content... ideias...

but when i finally tried memacs gives me error:

`time data '2022:07:01 24:33:02' does not match format '%Y:%m:%d %H:%M:%S'`

Any advice

Best regards
ArchGalileu

**Comment by novoid** [comment]
Hi,

The first thing I can see is that you're trying to parse "24 hours and 33 minutes" which does not exist. It's either "23 hours and 33 minutes" or "00 hours and 33 minutes" accordingly. 

For more, I would need further context on this message. Which of the modules in what version did you use on which data?

But in this case, I'd say the data does not represent a valid timestamp format as the error message also suggests.
