### ISSUE TITLE
suggest: screencast examples

### ISSUE THREAD

**Issue by nbehrnd** [novoid/Memacs#112]
The landing page of the [orger](https://github.com/karlicoss/orger) project mentions a [screencast](https://www.youtube.com/watch?v=ib_PDJpTh-Q) as an appetizer.  Memacs points to orger, and orger points to memacs as in programs with (partial) overlap of the aim set. Are there similar presentations about memacs you may recommend, or a recording of a talk of similar clarity like the one at [GLT18](https://www.youtube.com/watch?v=rckSVmYCH90) ?

Starting around 16:39 mm:ss of the [Emacs chat](https://www.youtube.com/watch?v=SaKPr4J0K2I) with Sacha Chua, Karl sheds some light on what already was possible back in 2014.  Since then, possibly some of the commands and the recommended workflows changed while new functions were implemented.  This could justify pointers to more recent recordings to showcase contemporary interaction with Memacs.

**Comment by novoid** [comment]
Screencast: what would you expect to see?

Setup of one of the many modules? (That's usually just a line in your crontab.)

Using the data collected in the resulting Orgdown files? (That's basic Org-mode functionality such as generating and using the agenda.)

Changed commands: the thing that happened in between was mostly more modules from peers were joining the repository. Most of them are not used by myself. I set up Memacs many years ago and it's modules are running "in background" ever since.

**Comment by nbehrnd** [comment]
An indication to the chat, perhaps amended by an illustration of an example where Memacs extends the agenda view as provided by default would be an appetizer.  The underlying .pdf I recored a screenphoto would suit well:

![2022-07-11T11 55 33 -- screenshots pim linked](https://user-images.githubusercontent.com/19709084/178240005-7ea95f8f-6dc9-45d2-9707-da77005c13dd.png)

A repeated attempt to use Memacs functionality, now in a virtual environment, suggest starting with the module about .csv data is problematic (separate thread), while installation and use of the one for photographs is easier.

**Comment by novoid** [comment]
Oh, the screenshot(s) from the linked whitepaper? OK, I can do that, if you do find this helpful.

**Comment by novoid** [comment]
Done, you'll find the screenshot from the paper in the README. Thanks for the suggestion!

**Comment by nbehrnd** [comment]
Karl Voit wrote:

> Done, you'll find the screenshot from the paper in the README. Thanks for the suggestion!
> 

«Un bon croquis vaut mieux qu'un long discours.»  Or, "A picture is
worth a thousand words."
