### ISSUE TITLE
suggest revision installation via pip, provision of test/reference data

### ISSUE THREAD

**Issue by nbehrnd** [novoid/Memacs#115]
The scope of files considered when installing Memacs with pip apparently is smaller than when running an installation with fork/clone from GitHub.

Cloning the project from GitHub offers path `/Memacs/memacs/tests/data/` including multiple files (like `example1.csv`) to get familiar how files to process should be formatted, or to check Memacs' working.  These reference files however seem absent when running an installation via Python's pip as if accidentally omitted/forgotten.

The observation refers to an instance of Linux Debian 12/bookworm, branch testing.

**Comment by novoid** [comment]
On the one hand side, I'd say that people installing memacs via pip don't want to have test data shipped. (My personal not so strong opinion.) If you do want to have all the files, clone it via git and GitHub.

On the other hand, I'm not that familiar with packaging to pip. Therefore, I truly don't know why some files are shipped and some aren't. Currently, my VirtualBox setup is broken (severe Linux issues with the default LTS kernel and VirtualBox-issues with the most recent kernel) so I only have one machine at hand which doesn't have memacs installed via pip.

Maybe somebody wants to help here and explain the behavior?

**Comment by nbehrnd** [comment]
I agree the mileage may vary.  Speaking for the example of the module about .csv data, reading `/Memacs/memacs/tests/csv_test.py` did not help me as much as `/Memacs/memacs/tests/data/example1.csv`.  Not so much because semi-colons are used as delimiter in the _c_ sv file; the documentation explicitly mentions this default, but because of the organization/sequence of entries.

+ string `"** <2012-02-23 Thu> Amazon"` in the file for testing is split into two sub strings
+ in `csv_test.py`, currency is an item ahead of the value (like the US American `$ 4.99`) while `example1.csv` adopts the pattern where units follows the number, e.g., `9,99 €`.

As so often, eventually, it is a question of convention.  The addition of the explicit note -- like in the already accepted and merged PR -- is a suitable compromise with only little maintenance for future releases; it doesn't require an update if the content of the test data (`Memacs/memacs/tests/data/`, GitHub path) are edited.
