### ISSUE TITLE
a few links in `README.org` are dysfunctional

### ISSUE THREAD

**Issue by nbehrnd** [novoid/Memacs#117]
The project's main documentation `README.org` includes a few links which do not work/do not work anymore.  The ones identified all belong to the incubator zone about code which eventually _might_ yield a module ready for production. 

In the screen photo below, the links are highlighted by blue rectangles:

![2022-07-15_Memacs_addresses_moved](https://user-images.githubusercontent.com/19709084/179254914-82508f1e-33a6-4b00-8b3a-35d9dba24e4b.png)

**Comment by novoid** [comment]
Thanks for the notification! I've once moved away all modules that were not using the generic Memacs framework (yet) to the tmp subdirectory without fixing their links in the readme file. Sorry for that.
