### ISSUE TITLE
suggest: extension of general README.org (though pending revision)

### ISSUE THREAD

**Issue by nbehrnd** [novoid/Memacs#118]
I would like to suggest an extension of the workflows described in the general `README.org`, namely, by an additional (explicit) example how to set up a call of one of the scripts from an running instance of Emacs orgmode.

Like you, I use an `emacs-config.org` which is translated into `emacs-config.el`.  In my case, this is based on a [tutorial-like](https://www.suenkler.info/emacs/emacs-config-systematik/) presentation by Hendrik Sünkler.  The observation is that addition of a block like

```org
    #+begin_src emacs-lisp
(defun my/test ()
  "write an empty file"
  (interactive)
    (shell-command
    (format "touch ~/Desktop/echo.txt")
    )
)

(add-hook 'org-mode-hook
  (lambda ()
    (add-hook 'before-save-hook 'my/test nil 'local)))
    #+end_src
```

yields a new entry among the commands, `M-x my/test` which successfully writes a new (empty) file.  By similar token

```org
    #+begin_src emacs-lisp
(defun my/test ()
  "write an empty file"
  (interactive)
    (shell-command
    (format "~/Desktop/test.py") 
    )
)

(add-hook 'org-mode-hook
  (lambda ()
    (add-hook 'before-save-hook 'my/test nil 'local)))
    #+end_src
```

allows to launch script `test.py`

```python
#!/usr/bin/env python3

import os
register = []

for file in os.listdir("."):
    register.append(file)

with open("survey.txt", mode="w") as newfile:
    for entry in register:
        newfile.write("".join([entry, "\n"]))
```

provided the script was previously given the executable bit (`chmod u+x ~/Desktop/test.py`).  Yet in principle, `test.py` equally could be a module of Memacs, too.

What I did not (yet) understand from reading inspiring examples by [John Kitchin](https://kitchingroup.cheme.cmu.edu/blog/2016/03/26/A-molecule-link-for-org-mode/) and [Rainer Koenig](http://koenig-haunstetten.de/2016/07/09/code-snippet-for-orgmode-e05s02/) about defining a function to access the shell of the OS / a more comfortable access to the function by a key-binding is how I eventually could access the function not only by `M-x 'some-word-combination'`, but by a keybinding like either `C-c U` (capital `U`) or a function key like `F5` (Rainer Koenig's example) to launch the intended _update_, provided e.g. by Memac's module about photos when returning from an excursion -- a run independent from the scheduled one by `cron`.

Given the seasoned `config.org` you maintain, may you identify the missing instructions I should add to the above definitions to add more comfortable key bindings?  In return, the example could enter the documentation right next to point 2 «When this script works as expected, set up a periodical invocation ...».

The observations refer to Linux Debian 12/bookworm (branch testing) with Python 3.10.5 and GNU bash 5.1.16(1) as shell.

**Comment by novoid** [comment]
Hi Bernd,

What is it, what you want to have accomplished here? An example setup process for one Memacs module?

How should Org-mode babel blocks help with that?

I mean, after all, each module invocation is one single line of Python with its command line parameters that vary from use-case to use-case...
