### ISSUE TITLE
memacs-imap and german umlauts are not working

### ISSUE THREAD

**Issue by thaaophz** [novoid/Memacs#20]
Hi,

last weekend I have installed memacs-imap and it works fine for mails
without umlauts. If a mail includes umlauts something goes wrong.

I set up memacs imap last weekend and it works fine for mails with no umlauts.
But if a mail includes umlauts something goes wrong.

For example an email with the Subject _"test ä ö ü ß"_ will be convertet to
_"test =?utf-8?B?w6Qgw7Ygw7wgw58=?="_.

I'm using OS X 10.10.2 with offlineimap.  
Actually I'm not sure if this is a memacs or an offlineimap problem because 
if I open the raw file from the maildirfolder the subject is also not displayed correctly. 
But there is no problem showing the mail in mu4e.

Is there anybody who can help me?

Thanks,
Matthias

**Comment by novoid** [comment]
Unfortunately, I don't use memacs with IMAP nor offlineimap nor mu4e.

Are you able to trace the issue further down and confirm if this is a memacs or an offlineimap issue?

**Comment by mattttthias** [comment]
I think the problem is that IMAP uses UTF-7 and not UTF-8.

I found a similar  issue and a solution [here] (http://stackoverflow.com/questions/12903893/python-imap-utf-8q-in-subject-string) :
```python
import email.Header
text, encoding = email.Header.decode_header('=?utf-8?Q?Subject?=')[0]
print(text)
Subject
```

While this works also for "correct" strings:
```python
text, encoding = email.Header.decode_header('test123')[0]
print(text)
test123
```
Maybe it is possible to decode every Subject and "From Name" so in the memacs script.

Sadly I dont't know which script I have to change.

**Comment by novoid** [comment]
In my opinion, the relevant lines are all within "memacs/memacs/lib/mailparser.py":

```
92:   output_from = MailParser.get_value_or_empty_str(headers, "From")
```
and
```
95:   subject = MailParser.get_value_or_empty_str(headers, "Subject", True)
```

You might want to add your decode statements, test them, and write back if it was successful. This would be great!

**Comment by mattttthias** [comment]
Till now it's not working.
But I'll keep working on it.

**Comment by manu09** [comment]
@novoid What do you use to track your mails into orgmode then? Is there any other way?

**Comment by novoid** [comment]
@manu09 Currently, I don't have any connection between my email setup and Orgmode.
