### ISSUE TITLE
use PEP 394 compliant shebang

### ISSUE THREAD

**Issue by mankoell** [novoid/Memacs#27]
I'm using Arch linux and the default `python` command refers to version **3.x**, which is not compatible with memacs. It wouldn't be python if there isn't already [a PEP standard](https://www.python.org/dev/peps/pep-0394/#abstract) for.

> This PEP provides a convention to ensure that Python scripts can continue to be portable across *nix systems, regardless of the default version of the Python interpreter (i.e. the version invoked by the python command).
> 
> - python2 will refer to some version of Python 2.x.
> - python3 will refer to some version of Python 3.x.
> - for the time being, all distributions should ensure that python refers to the same target as python2 .
> - however, end users should be aware that **python refers to python3 on at least Arch Linux** (that change is what prompted the creation of this PEP), so python should be used in the shebang line only for scripts that are source compatible with both Python 2 and 3.
> - in preparation for an eventual change in the default version of Python, Python 2 only scripts should either be updated to be source compatible with Python 3 or else to **use python2 in the shebang** line.

So would you mind changing it to `python2`?

**Comment by novoid** [comment]
Thanks for reporting this bug. Fixed with the latest commit.
