### ISSUE TITLE
memacs_lastfm fails, other modules work

### ISSUE THREAD

**Issue by ajft** [novoid/Memacs#45]
Karl, I've been using memacs for a few years, and a month ago included memacs_lastfm to get my music listings.  It was working for a few weeks, but following a system upgrade from ubuntu 17.10 to 18.04 the lastfm module has stopped working.  All the other memacs modules that I use still work, but memacs_lastfm crashes with:

Traceback (most recent call last):
     File "/home/ajft/src/memacs/memacs/lib/memacs.py", line 187, in handle_main
       self._main()
     File "/home/ajft/src/memacs/memacs/lastfm.py", line 76, in _main
       network = pylast.get_lastfm_network(**options)
   AttributeError: 'module' object has no attribute 'get_lastfm_network'
Traceback (most recent call last):
  File "/home/ajft/src/memacs/bin/memacs_lastfm.py", line 27, in <module>
    memacs.handle_main()
  File "/home/ajft/src/memacs/memacs/lib/memacs.py", line 187, in handle_main
    self._main()
  File "/home/ajft/src/memacs/memacs/lastfm.py", line 76, in _main
    network = pylast.get_lastfm_network(**options)
AttributeError: 'module' object has no attribute 'get_lastfm_network'
Makefile:131: recipe for target 'lastfm.org_archive' failed
make: *** [lastfm.org_archive] Error 1

Is this a problem with memacs_lastfm, or have i managed to break my own installation of python modules (something I know nothing about, but seem to have any number of system-wide ubuntu packages, pip packages, etc)

**Comment by novoid** [comment]
Hi ajft,

This looks like the pylast lib has changed in an incompatible way.

However, I don't use lastfm. The module was written by @glumanda99 who might be able to help here.

Thanks for reporting!

**Comment by ajft** [comment]
I'm not sure if what I did has just fixed it as a side effect, or if something else changed while I was poking about, but.

Hunting around I found that there was a version of memacs-0.4 in /usr/local/lib/python2.7, in addition to the current version elsewhere.  After I deleted the old version the script now runs.

thanks for your time, and many thanks for hte work on memacs

**Comment by novoid** [comment]
Thanks for the report and glad, that it's working now.

Greetings from Graz!
