### ISSUE TITLE
Failing Unittests

### ISSUE THREAD

**Issue by DerBeutlin** [novoid/Memacs#60]
I would like to help on porting memacs to python 3 #52 but first it would be nice to have passing unittests.
I tried to fix the obvious ones #59 but for some my knowledge of the system is not sufficient.

1) The GPX-Tests: For me the adress obtained differs from the expected one 
```
- ** <2017-04-01 Sat 10:50> Alte Poststraße 150, 8020 Graz, Austria	:network:
?                             ^ ----------  ^^^
+ ** <2017-04-01 Sat 10:50> Eggenberger Allee 9, 8020 Graz, Austria	:network:
? 
```
If the gps data has changed this should be an easy fix.

2) in `memacs.tests.example_test.TestFoo` and  `memacs.tests.rss_test.TestRss` it seems like a line should be inserted in between the heading and the `:PROPERTIES:`. But I am not sure if this is really the case or the intention

3) in `memacs.tests.simplephonelogs_test.TestSimplePhoneLogsFull` first of all the times are expected to be blank if they are equal to zero (e.g. when there is no shutdown before the boot) this should be fixed fairly quick if this is really the intention. Additionally the `:HOURS_RUNTIME_EXTRAPOLATION:` as well as the `OFFICE_SUMMARY:` are not expected by the tests.

It would be nice if you could tell me a bit about your intentions, then I might also be able to fix these tags.

**Comment by novoid** [comment]
Absolutely brilliant idea to go on with the test/migration tasks.
I'm going to help you - of course. However, I am out of town this weekend and then I'm pretty busy until August 20 or so. Therefore, I unfortunately can't help you until then :-(
I'll schedule the task so that I certainly don't forget it.

**Comment by novoid** [comment]
All mentioned unit tests are fixed on my machine. Please check it yourself and then let's close this issue.

**Comment by DerBeutlin** [comment]
Great thanks,

Unfortunately there is still one test failing on my machine:
```
FAIL: test_from_file (memacs.tests.svn_test.TestSvnMemacs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/max/git/memacs/memacs/tests/svn_test.py", line 44, in test_from_file
    "   added package to assignment1.tex for landscaping (see 5.tex)")
AssertionError: u'   :PROPERTIES:' != '   added package to assignment1.tex for landscaping (see 5.tex)'
```

Not sure if I overlooked it last time

**Comment by novoid** [comment]
Dear @DerBeutlin,
I did not start all unit tests myself. Sorry.
I fixed the `svn_test.py`.
Probably I should write a script that starts all unit tests at once...
