### ISSUE TITLE
Inactive Datetime in OrgFormat does not accept datetime object

### ISSUE THREAD

**Issue by DerBeutlin** [novoid/Memacs#72]
The[ inactive_datetime](https://github.com/novoid/Memacs/blob/522fc937db19a6efa003b2a14b50e4a499da93a8/memacs/lib/orgformat.py#L166) -function in does not accept datetime objects as parameters but only time.struct_times,
The very similar function [datetime](https://github.com/novoid/Memacs/blob/522fc937db19a6efa003b2a14b50e4a499da93a8/memacs/lib/orgformat.py#L156) does accept both.
Is there a reason for that?

**Comment by novoid** [comment]
Yes: laziness ;-)
