### ISSUE TITLE
Provide a NixOS package for Memacs

### ISSUE THREAD

**Issue by Spass1966** [novoid/Memacs#83]
Nix (of NixOS) allows you to write packages as self-contained, declarative services. Setting PATH  variables, cloning the repo, then setting cronjobs for each desired module is many steps in the way of a process that could be as simple as a `nix-env -i memacs`.

**Comment by novoid** [comment]
Hi @taohansen,

I am not familiar with NixOS.
Excuse me for asking: What is the issue you are reporting?

**Comment by taohansen** [comment]
Feature request, feel free to close!

**Comment by novoid** [comment]
Thanks for clarifying, @taohansen.
I can't provide this thing myself but I keep it here for reference in case somebody else might volunteer.

**Comment by novoid** [comment]
It doesn't seem that anybody is willing to help here. Please re-open if you want to send a pull request for providing NixOS package support.
